CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS EVENTS (
    ID UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    TITLE VARCHAR(25) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    LOCATION VARCHAR(25) NOT NULL,
    AVAILABLE_SLOTS INTEGER NOT NULL,
    ADMIN_ID UUID NOT NULL,
    FOREIGN KEY (ADMIN_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);