CREATE EXTENSION IF NOT EXISTS "pgcripto"

CREATE TABLE IF NOT EXISTS NOTIFICATIONS (
    ID UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    USER_ID UUID,
    MESSAGE VARCHAR(255) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);